name: Build
on:
  push:
    paths-ignore:
      - platforms.json
  workflow_dispatch: {}


jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev python3 python3-pip
        pip3 install pip --upgrade
        pip3 install -r requirements.txt --upgrade
        pip3 install pyopenssl --upgrade

    - name: Run build script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python3 build.py
    
  build-mac:
    name: Mac
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip3 install -r requirements.txt --upgrade

    - name: Run build script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python3 build.py

  build-win:
    name: Windows
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install -r requirements.txt --upgrade

    - name: Run build script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python build.py

  build-manifest:
    name: Python + Manifest
    runs-on: ubuntu-22.04
    needs: [build-linux, build-mac, build-win]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip3 install pip --upgrade
        pip3 install -r requirements.txt --upgrade

    - name: Run build script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python3 build.py --python --commit